/**
 * @file func.h
 * @brief Macro to represent Bool Function and Const
 * @date 2022-07-25
 *
 * @copyright Copyright (c) 2022. phanen
 *
 */

#
#include <stdint.h>

// Rotate left
#define ROTL(x, n) (((x) << (n)) | ((x) >> (32 - (n))))

// Permutation func
#define P0(x) ((x) ^ ROL32 ((x), 9) ^ ROL32 ((x), 17))
#define P1(x) ((x) ^ ROL32 ((x), 15) ^ ROL32 ((x), 23))

// Bool func
#define FF00(x, y, z) ((x) ^ (y) ^ (z))
#define FF16(x, y, z) (((x) & (y)) | ((x) & (z)) | ((y) & (z)))
#define GG00(x, y, z) ((x) ^ (y) ^ (z))
#define GG16(x, y, z) ((((y) ^ (z)) & (x)) ^ (z))

#define T00 0x79cc4519U
#define T16 0x7a879d8aU

// generated by rotl Txx
static uint32_t K[64] = {
  0x79cc4519U, 0xf3988a32U, 0xe7311465U, 0xce6228cbU, 0x9cc45197U, 0x3988a32fU,
  0x7311465eU, 0xe6228cbcU, 0xcc451979U, 0x988a32f3U, 0x311465e7U, 0x6228cbceU,
  0xc451979cU, 0x88a32f39U, 0x11465e73U, 0x228cbce6U, // 16
  0x9d8a7a87U, 0x3b14f50fU, 0x7629ea1eU, 0xec53d43cU, 0xd8a7a879U, 0xb14f50f3U,
  0x629ea1e7U, 0xc53d43ceU, 0x8a7a879dU, 0x14f50f3bU, 0x29ea1e76U, 0x53d43cecU,
  0xa7a879d8U, 0x4f50f3b1U, 0x9ea1e762U, 0x3d43cec5U, 0x7a879d8aU, 0xf50f3b14U,
  0xea1e7629U, 0xd43cec53U, 0xa879d8a7U, 0x50f3b14fU, 0xa1e7629eU, 0x43cec53dU,
  0x879d8a7aU, 0x0f3b14f5U, 0x1e7629eaU, 0x3cec53d4U, 0x79d8a7a8U, 0xf3b14f50U,
  0xe7629ea1U, 0xcec53d43U, 0x9d8a7a87U, 0x3b14f50fU, 0x7629ea1eU, 0xec53d43cU,
  0xd8a7a879U, 0xb14f50f3U, 0x629ea1e7U, 0xc53d43ceU, 0x8a7a879dU, 0x14f50f3bU,
  0x29ea1e76U, 0x53d43cecU, 0xa7a879d8U, 0x4f50f3b1U, 0x9ea1e762U, 0x3d43cec5U,
};