from rho_pollard import *
from pysmx.SM3 import hash_msg as hash_func

# hash_method = hash_func # Must be func which takes one argument, the clear message and returns the corresponding hash.
len_randWord_max = 1000  # Maximum length (in char) of the random word generated by Pollard's Rho algorithm

rho_pollard = Rho_pollard(hash_func, len_randWord_max)

(clear1, clear2,
 nb_hash) = rho_pollard.generateCollision()  # The called func returns the two clears message in collision and the number of hashes generated.
